Add handling for subscription not ack by broker
gojek/courier-android pull request #38
Opened 2022-07-28 08:01 UTC by rubenquadros12

When the client is trying to subscribe to topics if the broker is not able to subscribe successfully we get a SUBACK from broker with grantedQos of 128. In this case, currently we still get `MqttSubscribeSuccessEvent` form the library leading to false positives.  

The change is to provide a failure in this case which leads to retrying the subscription request internally and once the MAX retry is exhausted provide a `MqttSubscribeFailureEvent` to the client and keep retrying internally.

This handles the scenario where the broker has not successfully subscribed and the same is communicated to the client via the library.

https://github.com/gojek/courier-android/issues/37

2022-07-29 06:42 UTC, deepanshu42 commented
Hi @rubenquadros12, thanks for this PR

Few points and suggestions:
- A SUBACK can have multiple return codes(both success and failure) for multiple topics. So calling token.actionCallback failure is not correct.
- We can get MqttSuback packet in onSuccess of subscriptionlistener in MqttConnection class and based on return code we can send MqttSubscribeSuccess and Failure Events.
- We will not retry on 128 return code inside library. Retries are meant for network-related issues. User can retry from outside lib based on failure event.

2022-07-29 10:07 UTC, rubenquadros12 commented
Got you point on avoiding internal retrying but should we send both `MqttSubscribeSuccess` and `MqttSubscribeFailureEvent` since topics are not really subscribed? In my opinion only failure event should be sent. Please do let me know your thoughts.

2022-07-29 10:43 UTC, deepanshu42 commented
> 

`MqttSubscribeSuccessEvent` should be sent for topics which are successfully subscribed, if any.
`MqttSubscribeFailureEvent` should be sent for topics which are not successfully subscribed, if any.

2022-07-29 10:49 UTC, rubenquadros12 commented
Got it.. I was under the impression that if one topic fails we send fail for all topics since we are doing bulk subscription. Will send fail for only the failed ones 👍

2022-08-01 17:13 UTC, anubhav7nov commented on paho/src/main/java/org/eclipse/paho/client/mqttv3/internal/Token.java
> +	public int[] getGrantedQos() {
i think we can avoid this here. We are exposing wiremessage. We can utilise that

2022-08-02 11:08 UTC, deepanshu42 requested changes

2022-08-02 11:08 UTC, deepanshu42 commented on mqtt-client/src/main/java/com/gojek/mqtt/connection/MqttConnection.kt
> +                        failTopicMap[topic] = topicMap[topic] ?: ONE
use force-dereference `!!`. topic should always be present in `topicMap`

2022-08-02 11:08 UTC, deepanshu42 commented on mqtt-client/src/main/java/com/gojek/mqtt/connection/MqttConnection.kt
> +                        successTopicMap[topic] = topicMap[topic] ?: ONE
use force-dereference `!!`. topic should always be present in `topicMap`

2022-08-03 06:34 UTC, rubenquadros12 commented on paho/src/main/java/org/eclipse/paho/client/mqttv3/MqttException.java
> +	public static final short REASON_CODE_SUBSCRIPTION_NOT_ACK = 32204;
Invalid subscription could also mean where the topic name is something like `abc#`. In this case we should directly get a failure callback when subscribe is called.  Please suggest any other alternative and will change it. Issue for reference: https://github.com/gojek/courier-android/issues/32

2022-08-05 11:07 UTC, anubhav7nov commented on paho/src/main/java/org/eclipse/paho/client/mqttv3/MqttException.java
> +	public static final short REASON_CODE_SUBSCRIPTION_NOT_ACK = 32204;
hey @rubenquadros12 still it's a REASON_CODE_INVALID_SUBSCRIPTION. For #32 that is also an invalid subscription

2022-08-05 12:41 UTC, rubenquadros12 commented on paho/src/main/java/org/eclipse/paho/client/mqttv3/MqttException.java
> +	public static final short REASON_CODE_SUBSCRIPTION_NOT_ACK = 32204;
Got it, have renamed the flag

2022-08-06 07:24 UTC, deepanshu42 approved these changes

2022-08-08 05:56 UTC, dilraj-singh1997 approved these changes

2022-08-09 11:13 UTC, merged