Replace "java.util.Optional" String with `class.java.name` to prevent…
gojek/courier-android pull request #89
Opened 2024-10-28 18:09 UTC by MohammadEhsanMohit

When the project uses desugaring to replace `java.util.Optional`, it can lead to exceptions in the Courier library on Android devices that do not support Java 8. To prevent this issue, it is advisable to use `Optional::class.java.name`, as this approach avoids any unintended changes introduced by R8 or desugaring processes. Additionally, since devices running Android versions lower than 7 do not support Java 8, there is no need to implement specific checks for these devices, as they will inherently be excluded from Java 8 features.

2024-11-06 05:13 UTC, sumitjat3 commented
@MohammadEhsanMohit  Change LGTM, hoping you've verified the changes and it's fixing the given crash.

Thanks for contribution

2024-11-06 06:49 UTC, sumitjat3 requested changes

2024-11-06 06:49 UTC, sumitjat3 commented on buildSrc/src/main/kotlin/deps.kt
> +}
Can you revert these changes

2024-11-06 11:15 UTC, MohammadEhsanMohit commented on buildSrc/src/main/kotlin/deps.kt
> +}
Done!

2024-11-06 11:17 UTC, sumitjat3 approved these changes

2024-11-11 03:03 UTC, deepanshu42 commented
Hi @MohammadEhsanMohit thank you for contribution. Changes look good, will merge and publish a new version of courier android library.

2024-11-11 03:03 UTC, deepanshu42 approved these changes

2024-11-11 03:13 UTC, merged